
.PHONY: all clean

all: p1.out p2.out p3.out p4.out

clean:
	rm -f p1.out p2.out p3.out p4.out

p1.out: p1.c
	gcc -o p1.out p1.c -Wall

p2.out: p2.c
	gcc -o p2.out p2.c -Wall

p3.out: p3.c
	gcc -o p3.out p3.c -Wall

p4.out: p4.c
	gcc -o p4.out p4.c -Wall

